POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "katri123",
  "name": "Katri Virtanen",
  "password": "salasana123"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "ab",
  "name": "Too Short Username",
  "password": "salasana123"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "validuser",
  "name": "Too Short Password",
  "password": "ab"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "katri",
  "name": "Duplicate Username",
  "password": "salasana123"
}

###

GET http://localhost:3003/api/users